import { Project } from '../models/project.model';
import { Task } from '../models/task.model';

export const MOCK_PROJECTS: Project[] = [
  {
    id: 1,
    name: 'Bygga hemsida',
    description: 'Projekt för att skapa en ny företagshemsida',
    deadline: '2025-07-31',
    tasks: [
      {
        id: 101,
        name: 'Designa layout',
        description: 'Skapa en modern och responsiv design',
        deadline: '2025-06-15',
        priority: 'high',
        status: 'Started',
        tags: ['design', 'UI'],
      },
      {
        id: 102,
        name: 'Implementera frontend',
        description: 'Bygga frontend med Angular',
        deadline: '2025-07-01',
        priority: 'medium',
        status: 'noStart',
        tags: ['frontend', 'angular'],
      },
      {
        id: 103,
        name: 'Implementera frontend',
        description: 'Bygga frontend med Angular',
        deadline: '2025-07-01',
        priority: 'medium',
        status: 'Done',
        tags: ['frontend', 'angular'],
      },
      {
        id: 104,
        name: 'Implementera frontend',
        description: 'Bygga frontend med Angular',
        deadline: '2025-06-16',
        priority: '',
        status: 'noStart',
        tags: ['frontend', 'angular'],
      },
      {
        id: 105,
        name: 'Implementera frontend',
        description: 'Bygga frontend med Angular',
        deadline: '',
        priority: '',
        status: 'Started',
        tags: ['frontend', 'angular'],
      },
    ],
  },
  {
    id: 2,
    name: 'Marknadsföringskampanj',
    description: 'Planera och genomföra en kampanj för produktlansering',
    deadline: '2025-08-15',
    tasks: [
      {
        id: 201,
        name: 'Skapa kampanjmaterial',
        description: 'Utforma flyers, annonser och sociala medier-inlägg',
        deadline: '2025-07-10',
        priority: 'medium',
        status: 'noStart',
        tags: ['marketing', 'graphics'],
      },
      {
        id: 202,
        name: 'Planera annonsering',
        description: 'Välj kanaler och budget för annonsering',
        deadline: '2025-07-20',
        priority: 'low',
        status: 'noStart',
        tags: ['planning', 'ads'],
      },
    ],
  },
  {
    id: 3,
    name: 'Webbshop för e-handel',
    description: 'Planera och skapa en webbshop för e-handel',
    deadline: '2025-06-16',
    tasks: [
      {
        id: 301,
        name: 'Skapa Figma design',
        description: 'Gör en utförlig design i Figma för webbshoppen',
        deadline: '2025-07-10',
        priority: 'medium',
        status: 'noStart',
        tags: ['marketing', 'graphics'],
      },
      {
        id: 302,
        name: 'Planera annonsering',
        description: 'Välj kanaler och budget för annonsering',
        deadline: '2025-07-20',
        priority: 'low',
        status: 'noStart',
        tags: ['planning', 'ads'],
      },
      {
        id: 303,
        name: 'Skapa produktkatalog',
        description: 'Samla och strukturera produktinformation för webbshoppen',
        deadline: '2025-06-03',
        priority: 'high',
        status: 'noStart',
        tags: ['produkter', 'katalog'],
      },
    ],
  },
];
